<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>OBS Recordings Transfer Setup</AssemblyName>
    <RootNamespace>OBS.RecordingsTransfer.Installer</RootNamespace>
    <Version>2.0.0</Version>
    <Company>chasemsutton</Company>
    <Product>OBS Recordings Transfer Setup</Product>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\app.zip" Condition="Exists('Payload\app.zip')" />
  </ItemGroup>

</Project>
